version: '3.8'
services: # apps containers you want to build and run
  madhuriapp1: # name of appliction for compose
    image: madhuridotnetimg:v1  # image i want to build
    build: .  # path of dockerfile location -- . means current
    container_name: madhuric1 # it will create container also
